---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sitejsvh/WorkflowTest2.sitesystemhub.com/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH